- name: Uninstall NGINX
  hosts: all
  become: yes
  tasks:
    - name: Remove NGINX package
      ansible.builtin.package:
        name: nginx
        state: absent

    - name: Remove NGINX configuration directory (optional)
      ansible.builtin.file:
        path: /etc/nginx
        state: absent

    - name: Remove NGINX default HTML files (optional)
      ansible.builtin.file:
        path: /var/www/html
        state: absent
